// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handler

import (
	"context"

	"github.com/VV1nc3nt/items/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockItemManagerService creates a new instance of MockItemManagerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockItemManagerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockItemManagerService {
	mock := &MockItemManagerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockItemManagerService is an autogenerated mock type for the ItemManagerService type
type MockItemManagerService struct {
	mock.Mock
}

type MockItemManagerService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockItemManagerService) EXPECT() *MockItemManagerService_Expecter {
	return &MockItemManagerService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockItemManagerService
func (_mock *MockItemManagerService) Create(ctx context.Context, req *model.ItemCreateInput) (*model.Item, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.ItemCreateInput) (*model.Item, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.ItemCreateInput) *model.Item); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.ItemCreateInput) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockItemManagerService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockItemManagerService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - req *model.ItemCreateInput
func (_e *MockItemManagerService_Expecter) Create(ctx any, req any) *MockItemManagerService_Create_Call {
	return &MockItemManagerService_Create_Call{Call: _e.mock.On("Create", ctx, req)}
}

func (_c *MockItemManagerService_Create_Call) Run(run func(ctx context.Context, req *model.ItemCreateInput)) *MockItemManagerService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.ItemCreateInput
		if args[1] != nil {
			arg1 = args[1].(*model.ItemCreateInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockItemManagerService_Create_Call) Return(item *model.Item, err error) *MockItemManagerService_Create_Call {
	_c.Call.Return(item, err)
	return _c
}

func (_c *MockItemManagerService_Create_Call) RunAndReturn(run func(ctx context.Context, req *model.ItemCreateInput) (*model.Item, error)) *MockItemManagerService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockItemManagerService
func (_mock *MockItemManagerService) Get(ctx context.Context, req *model.ItemGetInput) (*model.Item, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.ItemGetInput) (*model.Item, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.ItemGetInput) *model.Item); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.ItemGetInput) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockItemManagerService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockItemManagerService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - req *model.ItemGetInput
func (_e *MockItemManagerService_Expecter) Get(ctx any, req any) *MockItemManagerService_Get_Call {
	return &MockItemManagerService_Get_Call{Call: _e.mock.On("Get", ctx, req)}
}

func (_c *MockItemManagerService_Get_Call) Run(run func(ctx context.Context, req *model.ItemGetInput)) *MockItemManagerService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.ItemGetInput
		if args[1] != nil {
			arg1 = args[1].(*model.ItemGetInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockItemManagerService_Get_Call) Return(item *model.Item, err error) *MockItemManagerService_Get_Call {
	_c.Call.Return(item, err)
	return _c
}

func (_c *MockItemManagerService_Get_Call) RunAndReturn(run func(ctx context.Context, req *model.ItemGetInput) (*model.Item, error)) *MockItemManagerService_Get_Call {
	_c.Call.Return(run)
	return _c
}
