// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package itemmanagermock

import (
	"context"

	"github.com/VV1nc3nt/items/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockRepository
func (_mock *MockRepository) Create(ctx context.Context, in *model.ItemInput) (model.Item, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 model.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.ItemInput) (model.Item, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.ItemInput) model.Item); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Get(0).(model.Item)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.ItemInput) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - in *model.ItemInput
func (_e *MockRepository_Expecter) Create(ctx any, in any) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, in)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, in *model.ItemInput)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.ItemInput
		if args[1] != nil {
			arg1 = args[1].(*model.ItemInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(item model.Item, err error) *MockRepository_Create_Call {
	_c.Call.Return(item, err)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(ctx context.Context, in *model.ItemInput) (model.Item, error)) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}
