// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package item_manager

import (
	"context"

	"github.com/VV1nc3nt/items/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockrepository creates a new instance of Mockrepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockrepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mockrepository {
	mock := &Mockrepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Mockrepository is an autogenerated mock type for the repository type
type Mockrepository struct {
	mock.Mock
}

type Mockrepository_Expecter struct {
	mock *mock.Mock
}

func (_m *Mockrepository) EXPECT() *Mockrepository_Expecter {
	return &Mockrepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type Mockrepository
func (_mock *Mockrepository) Create(ctx context.Context, in *model.ItemCreateInput) (model.Item, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 model.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.ItemCreateInput) (model.Item, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.ItemCreateInput) model.Item); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Get(0).(model.Item)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.ItemCreateInput) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Mockrepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type Mockrepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - in *model.ItemCreateInput
func (_e *Mockrepository_Expecter) Create(ctx any, in any) *Mockrepository_Create_Call {
	return &Mockrepository_Create_Call{Call: _e.mock.On("Create", ctx, in)}
}

func (_c *Mockrepository_Create_Call) Run(run func(ctx context.Context, in *model.ItemCreateInput)) *Mockrepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.ItemCreateInput
		if args[1] != nil {
			arg1 = args[1].(*model.ItemCreateInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Mockrepository_Create_Call) Return(item model.Item, err error) *Mockrepository_Create_Call {
	_c.Call.Return(item, err)
	return _c
}

func (_c *Mockrepository_Create_Call) RunAndReturn(run func(ctx context.Context, in *model.ItemCreateInput) (model.Item, error)) *Mockrepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type Mockrepository
func (_mock *Mockrepository) Get(ctx context.Context, in *model.ItemGetInput) (model.Item, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.ItemGetInput) (model.Item, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.ItemGetInput) model.Item); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Get(0).(model.Item)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.ItemGetInput) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Mockrepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type Mockrepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - in *model.ItemGetInput
func (_e *Mockrepository_Expecter) Get(ctx any, in any) *Mockrepository_Get_Call {
	return &Mockrepository_Get_Call{Call: _e.mock.On("Get", ctx, in)}
}

func (_c *Mockrepository_Get_Call) Run(run func(ctx context.Context, in *model.ItemGetInput)) *Mockrepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.ItemGetInput
		if args[1] != nil {
			arg1 = args[1].(*model.ItemGetInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Mockrepository_Get_Call) Return(item model.Item, err error) *Mockrepository_Get_Call {
	_c.Call.Return(item, err)
	return _c
}

func (_c *Mockrepository_Get_Call) RunAndReturn(run func(ctx context.Context, in *model.ItemGetInput) (model.Item, error)) *Mockrepository_Get_Call {
	_c.Call.Return(run)
	return _c
}
