all: false
recursive: true
template: testify
formatter: goimports
dir: "{{.InterfaceDir}}"
filename: "mock_{{.InterfaceName | snakecase}}.go"
pkgname: "{{.SrcPackageName}}"
structname: "Mock{{.InterfaceName}}"
packages:
  github.com/VV1nc3nt/items: